manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: edgehog-device-manager
      url-base: https://github.com/edgehog-device-manager
    - name: sorru94
      url-base: https://github.com/sorru94

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.2.1
      import: true
    - name: edgehog-device-manager
      remote: sorru94
      repo-path: edgehog-zephyr-device.git
      revision: small-fixes-to-scripts
